
---
- hosts: nifi-cluster
  vars:
    nifi-user: nifi
    nifi-shell: /bin/bash

  tasks:
    - name: Create nifi user
      user:
        name: "{{ nifi-user }}"
        password: ni1Q9uPjsIJo6
        comment: "nifi service account"
        uid: 1040
        shell: {{ nifi-shell }}
        createhome: yes