
---
- hosts: nifi-cluster
  vars:
    nifi-source: http://mirror.csclub.uwaterloo.ca/apache/nifi/1.5.0/nifi-1.5.0-bin.tar.gz
    nifi-pkg-name: nifi-1.5.0-bin.tar.gz
    nifi-pkg-checksum: 93712c73e2981228f3b2cdcb56024d4e99a4a2559d6a22fb22e85a616dbf20a3
    nifi-version: nifi-1.5.0
    nifi-install-dir: /opt/nifi
    nifi-owner: nifi
    nifi-mode: 0750

  tasks:
    - name: Create installation directory
      file:
        path: "{{ nifi-install-dir }}"
        owner: "{{ nifi-owner }}"
        mode: "{{ nifi-mode }}"
        state: directory

    - name: Download from apache nifi website
      get_url:
        url: "{{ nifi-source }}"
        dest: "{{ nifi-install-dir }}"
        checksum: "sha256:{{ nifi-pkg-checksum }}"
        owner: "{{ nifi-owner }}"
        mode: "{{ nifi-mode }}"

    - name: Unarchive nifi tarball
      unarchive:
        src: "{{ nifi-install-dir }}/{{ nifi-pkg-name }}"
        dest: "{{ nifi-install-dir }}"
        remote_src: yes
        owner: "{{ nifi-owner }}"
        mode: "{{ nifi-mode }}"

    - name: Delete downloaded tarball
      file:
        path: "{{ nifi-install-dir }}/{{ nifi-pkg-name }}"
        state: absent